server = "livestatus.local:50000"
refresh = 30
hosts_pattern = [".prod.", ".dev.", ".staging."]
popup = true
warnings = true
debug = false
get_duration = false
limit = 0
# notes_url = true
# notification_snooze_cycle = 20
# auto_stop = "* 12-15 * * *"
# auto_start = "* 15-19 * * *"
